### ISSUE TITLE
convincing argument for the sustainability of the course

### ISSUE THREAD

**Issue by SaraMati** [UofTCoders/grad-course#1]
One requested item to be in the proposal is a sustainability plan, i.e. how the quality of the course is maintained after the first year that we teach it. (since the main developers of the course will graduate, is it guaranteed that the next instructors keep the quality?)

- this is a open source course, meaning that all the content is accessible on the website, the main developers and public audience can always track the changes to the content 
- because of the 'participatory live-coding' principle that the course content is based on, this means that each session's content is planned in detail so there is no room for individuals deciding on cutting the content. even if the situations mandate the instructor to cut the content while teaching, it will be available to the students online. 
- rcourse experience: second year only two people out of 4 taught it and the two new people could teach 
- the material is heavily documented
- it's based on the fundamentals of scientific workflow and reproducible science
- the course syllabus is designed as the participatory live coding, hence every lecture is defined in detail

**Comment by lwjohnst86** [comment]
Really nice arguments here.

I would also add that the course content will be hosted on a publicly accessible website url, that others can easily take from and add to or update.
